var k3_lang = {
    'Hae': "Hae",
    'Uutta_viestia': "uutta viestiä",
    'Uusia_kalenterimerkintaa': "Uudet kalenterimerkinnät",
    'Lukematonta_uutista': "lukematonta uutista",
    'Ei_uusia_viesteja': "Ei lukemattomia viestejä",
    'Uusi_viesti': "uusi viesti",
    'Uusi_kalenterimerkinta': "Uusi kalenterimerkintä",
    'Lukematon_uutinen': "Lukematon uutinen",
    'Muistilappuja': "Muistilappuja",
    'Muistilappu': "Muistilappu",
    'Muistutus': "Muistutus",
    'Sulje': "Sulje",
    'monthNames': new Array('Tammikuu','Helmikuu','Maaliskuu','Huhtikuu','Toukokuu','Kesäkuu','Heinäkuu','Elokuu','Syyskuu','Lokakuu','Marraskuu','Joulukuu'),
    'monthNamesShort': new Array('Tammi','Helmi','Maalis','Huhti','Touko','Kesä','Heinä','Elo','Syys','Loka','Marras','Joulu'),
    'dayNamesMin': new Array('Su','Ma','Ti','Ke','To','Pe','La'),
    'Tyhjenna': "Tyhjennä",
    'Tanaan': "Tänään",
    'Valitse_paivamaara': "Valitse päivämäärä",
    'Lahettaa': "Lähettää",
    'Muokkaa': "Muokkaa",
    'muokkaa': "Muokkaa",
    'poista': "Poista",
    'Haluatko_varmasti_poistaa_muistutuksen': "Haluatko varmasti poistaa muistutuksen?",
    'OK': "OK",
    'Peruuta': "Peruuta",
    'Tallenna': "Tallenna",
    'Poista': "Poista",
    'Poista_muistutus': "Poista muistutus",
    'Valitse_aika': "Valitse aika",
    'Aika': "Aika",
    'Tunti': "Tunti",
    'Minuutti': "Minuutti",
    'Nyt': "Nyt",
    'Tietoja_haetaan': "Tietoja haetaan...",
    'Ei_osuumia': "Ei osumia",
    'Paallekkaisyys_ei_viela_tarkistettu': "Päällekkäisyyttä ei ole vielä tarkistettu",
    'Kustannuspaikka_ei_maaritetty': "Määritä toinen kustannuspaikka",
    'Ei_paallekkaisyyksia': "Ei päällekkäisyyksiä",
    'Paallekkainen_varaus': "Päällekkäinen varaus",
    'Linkitetty_paallekkaisyys': "Tila, jota olet varaamassa on määritelty kuuluvaksi tilaryhmään.<br />Varaus sopisi valitsemaasi tilaan, mutta samaan ryhmään kuuluvissa tiloissa on samanaikaisia varauksia.",
    'resurssi_varattu': "resurssi varattu",
    'resurssia_varattu': "resurssia varattu",
    'varoitus': "Varoitus!",
    'varaus_pois_1': "Tällä toiminnolla poistetaan varaus pysyvästi koko varauskirjasta.",
    'varaus_pois_2': "Mikäli varauksessa on useita käyttäjiä, poistetaan varaus kaikilta.",
    'varaus_pois_3': "Haluatko poistaa varauksen?",
    'varaus_pois_4': "Varauksesta on luotu myös Ilmoittautumislomake.",
    'varaus_pois_5': "Jos lomake on tarpeeton, poista se Ilmoittautuminen-sivulla.",
    'varaukset_pois_1': "Tällä toiminnolla poistetaan varaukset pysyvästi koko varauskirjasta.",
    'varaukset_pois_2': "Mikäli varauksissa on useita käyttäjiä, poistetaan varaukset kaikilta.",
    'varaukset_pois_3': "Haluatko poistaa varaukset?",
    'varaukset_pois_4': "Varauksista on luotu myös Ilmoittautumislomakkeita.",
    'varaukset_pois_5': "Jos lomakkeet ovat tarpeettomia, poista ne Ilmoittautuminen-sivulla.",
    'Aseta_tilan_kustannuspaikka': "Aseta tilan kustannuspaikka",
    'Valitse_ensin_kustannuspaikka': "Valitse ensin kustannuspaikka!",
    'tapahtuma_pois': "Haluatko poistaa yksityisen menon?",
    'tapahtumat_pois': "Haluatko poistaa kaikki yksityiset menot?",
    'Lasku': "Lasku",
    'Laskutustiedot': "Laskutustiedot",
    'Valmis': "Valmis",
    'Laheta': "Lähetä",
    'Luo': "Luo",
    'Aikavalinta': "Aikavalinta",
    'Sulje_ikkuna': "Sulje ikkuna",
    'Kaikki_tilat_lisattyina': "Kaikki tilat ovat jo lisättyinä",
    'Kaikki_henkilot_lisattyina': "Kaikki henkilöt ovat jo lisättyinä",
    'Ei_yhtaan_henkiloa_lisattyna': "Ei yhtään henkilöä lisättynä",
    'Valitse_kaikki': "Valitse kaikki",
    'Poista_valinnat': "Poista valinnat",
    'Aseta_tilan_lampotila': "Aseta tilan lämpötila",
    'Yllapitolampo': "Ylläpitolämpö",
    'Ei_lampoa': "Ei lämpöä",
    'Standardilampo': "Standardilämpö",
    'Tiedotus_lehteen_www': "Tiedotus lehteen/www",
    'Luokitus_tyhja': "Luokitus puuttuu",
    'Luokitus_tyhja_2': "Luokitus puuttuu, lisää se ja tallenna!",
    'Otsikko_tyhja': "Otsikko ei saa olla tyhjä",
    'Alkaa_pvm_virheellinen': "Alkaa pvm on virheellinen",
    'Loppuu_pvm_virheellinen': "Loppuu pvm on virheellinen",
    'Loppuu_pvm_aikaisempi_kuin_alkaa_pvm': "Loppuu pvm on aikaisempi kuin alkaa pvm",
    'Alkaa_klo_virheellinen': "Alkaa klo on virheellinen",
    'Loppuu_klo_virheellinen': "Loppuu klo on virheellinen",
    'Alkaa_klo_ja_loppuu_klo_samat': "Alkaa klo ja loppuu klo eivät saa olla samat",
    'Loppuu_klo_aikaisempi_kuin_alkaa_klo': "Loppuu klo on aikaisempi kuin alkaa klo",
    'Tiedote_tallennettu': "Tiedote tallennettu",
    'Tiedoteen_poiston_vahvistus': "Haluatko varmasti poistaa tiedotteen?",
    'Tiedoteen_poiston_vahvistus2': "Haluatko varmasti poistaa tiedotteet sekä netistä että lehdestä?",
    'Tiedote_poistettu': "Tiedote poistettu",
    'Lisaa_tiedotus_lehteen_www': "Lisää tiedotus lehteen/www",
    'Tiedotus_lehteen_www_on': "Tiedotus lehteen/www on",
    'kaupunginosa_pitaa_valita': "Kaupunginosa pitää olla valittuna!",
    'Tarjoiluvaraus': "Tarjoiluvaraus",
    'Tarjoiluvaraus_poistettu': "Tarjoiluvaraus poistettu",
    'Tarjoiluvaraukset_poistettu': "Tarjoiluvaraukset poistettu",
    'Lisaa_tarjoiluvaraus': "Lisää tarjoiluvaraus",
    'Poista_rivi': "Poista rivi",
    'Virheellinen_arvo': "Virheellinen arvo",
    'Tarjoiluvarauksen_poiston_vahvistus': "Haluatko varmasti poistaa tarjoiluvarauksen?",
    'Tarjoiluvarauksien_poiston_vahvistus': "Haluatko varmasti poistaa kaikki tarjoiluvaraukset?",
    'Tarjoiluvaraus_tallennettu': "Tarjoiluvaraus tallennettu",
    'Tarjoiluvaraukset_tallennettu': "Tarjoiluvaraukset tallennettu",
    'Tarjoiluvaraus_on': "Tarjoiluvaraus on",
    'avaa_jps_otsikko': "Jumalanpalvelusuunnitelma",
    'Avaataanko_jps': "Avataanko Jumalanpalvelussuunnittelu?",
    'lisaa': "Lisää",
    'kylla': "Kyllä",
    'ei': "Ei",
    'Valitse': "Valitse",
    'Lisaa_henkiloita': "Lisää henkilöitä",
    'Poista_henkiloita': "Poista henkilöitä",
    'Lisaa_tiloja': "Lisää tiloja",
    'aseta_osallistujamaara': "Tallenna osallistujamäärä",
    'aseta_kavijamaara': "Aseta kävijämäärä",
    'ohje': "Ohje",
    'kavijamaara_ohje_otsikko': "Kävijämäärän syöttöohje",
    'osallistujamaara_ohje_otsikko': "Osallistujamäärän tallennusohje",
    'kavijamaara_ohje_sisalto': "Lisää osallistujamäärä ja tallenna Tallenna painikkeella tai ENTER-näppäimellä.<br /><br />Suuressa osassa varauksia riittää kokonaisosallistujamäärän lisääminen vasemmanpuoleiseen laatikkoon.<br /><br />Tilaisuuksista, joissa vietetään ehtoollista, merkitse vasemmanpuoleiseen laatikkoon kokonaisosallistujamäärä ja oikeanpuoleiseen laatikkoon ehtollisella käyneiden määrä.",
    'ka_osallistujamaara_ohje': "Keskimääräinen osallistujamäärä tallennettu aiemmin Lisätiedot tilastointiin ikkunassa. Nyt tallennettavaa lukumäärää ei oteta huomioon vietäessä tilastoja kirkkohallitukseen.",
    'ka_osallistujamaara_ohje_vuosi': "Jos varausketjussa on varauksia myös seuraavalle vuodelle, lasketaan keskimääräinen osallistujamäärä ensimmäisen vuoden kokoontumisten osallistujien keskiarvona ja viedään kirkkohallituksen tilastojärjestelmään vuoden vaihtuessa.",
    'tallenna_kaikki': "Tallenna kaikki",
    'kayttajan_tiedot': "Käyttäjän tiedot",
    'tilan_tiedot': "Tilan tiedot",
    'salasanan_palautus': "Salasanan palautus",
    'salasanan_palautus_info_1': "Tarvitsemme käyttäjätunnuksesi, jotta voimme luoda uuden salasanan unohtuneen tilalle.",
    'salasanan_palautus_info_2': "Uusi salasana lähetetään sähköpostilla sinulle.",
    'tunnus': "Tunnus",
    'luo_uusi': "Luo uusi",
    'tyhja_tunnus': "Tunnus ei saa olla tyhjä",
    'tietoja_lahetetaan': "Odota, tietoja lähetetään...",
    'salasanan_vaihto_ok': "Uusi salasana on luotu ja lähetetty sähköpostiisi!",
    'salasanan_vaihto_virhe': "Uuden salasanan luonti epäonnistui!",
    'x_varattu_aikana': "%s varattu aikana",
    'Haku': "Haku",
    'Resurssin_kellonaika_lukittu': "Resurssin kellonaika lukittu",
    'Resurssin_kellonaika_vapaa': "Resurssin kellonaika vapaa",
    'Kayttajat': "Käyttäjät",
    'Tilat': "Tilat",
    'Paallekkaisia_aikoja_varaus': "Päällekkäisiä aikoja, varausta ei tallennettu.",
    'Paallekkaisia_aikoja': "Päällekkäisiä aikoja.",
    'Poistutaanko_tallentamatta': "Poistutaanko tallentamatta?",
    'Toistuvaa_varausta_ei_voi_muuttaa_jatkuvaksi': "Toistuvaa varausta ei voi muuttaa jatkuvaksi!",
    'Kayttajan_x_menot': "Käyttäjän %s menot",
    'Varausvahvistus_ei_sahkopostiosoitteita': "Yhtään sähköpostiosoitetta ei lisätty Varausvahvistus kenttään!",
    'Varausvahvistus_lahetetty_onnistuneesti': "Varausvahvistus lähetetty onnistuneesti valituille henkilöille!",
    'Muuta_kaikki': "Muuta kaikki",
    'Paivita_vain_tehdyt_muutokset': "Päivitä vain tehdyt muutokset",
    'Muutokset_alkaen': "Muutokset alkaen",
    'Paaryhma': "Pääryhmä",
    'Alkuaika': "Alkuaika",
    'Loppuaika': "Loppuaika",
    'Varaustyyppi': "Varaustyyppi",
    'Vapaatyyppi': "Vapaatyyppi",
    'Kustannuspaikka': "Kustannuspaikka",
    'Tilaisuuteen_tarvitaan': "Tilaisuuteen tarvitaan",
    'Selite': "Selite",
    'Lisaselite_suljettu': "Lisäselite (suljettu)",
    'Yhteyshenkilo': "Yhteyshenkilö",
    'Seurattava_varaus': "Seurattava varaus",
    'Laskutettava_tilaisuus': "Laskutettava tilaisuus",
    'Siivottava_tilaisuus': "Siivottava tilaisuus",
    'Asiakas': "Asiakas",
    'Vie_vuosikalenteriin': "Vie vuosikalenteriin",
    'Tiedotus_lehteen_www_pakollinen': "Tiedotus lehteen/www pakollinen valitulle varaustyypille!",
    'Tiedotus_lehteen_www_estetty': "Tiedotus lehteen/www estetty valitulle varaustyypille!",
    'Laskutettava_tilaisuus_pakollinen': "Laskutettava tilaisuus pakollinen valitulle varaustyypille!",
    'Linkki_virheellinen': "Linkki on virheellinen!",
    'Maarita_aloitusaika': "Määritä aloitusaika",
    'Maarita_lopetusaika': "Määritä lopetusaika",
    'Maarita_aloitus_ja_lopetusaika': "Määritä aloitus- ja lopetusaika",
    'Maarita_alkuaika_tyovuoro_info': "Valitse ensin työvuoron alkuaika<br />ja paina Tallenna -nappia.",
    'Maarita_loppuaika_tyovuoro_info': "Valitse työvuoron loppuaika ja<br />tallenna Tallenna -nappia painamalla.",
    'Vastuuhenkiloa_ei_valittu': "Vastuuhenkilöä ei valittu!",
    'Vastuuhenkilon_puhnro_tyhja': "Vastuuhenkilön puhelinnumero ei saa olla tyhjä!",
    'Vastuuhenkilon_poisto_estetty': "Vastuuhenkilöksi merkittyä käyttäjää ei voi poistaa!",
    'Toista_aina': "Toista aina",
    'Toista': "Toista",
    'viikon_valein': "viikon välein",
    'Alkaa': "Alkaa",
    'Loppuu': "Loppuu",
    'Maarita_toistuvuus': "Määritä toistuvuus",
    'Ilmoittaudu_tapahtumaan': "Ilmoittaudu tapahtumaan",
    'Ilmoittautuneen_tiedot': "Ilmoittautuneen tiedot",
    'haluatko_poistaa_ilm': "Haluatko varmasti poistaa ilmoittautuneen",
    'huom_ksync': "HUOM! Henkilön poisto pitää tehdä myös Kirjurin kautta",
    'Aseta_oikeudet': "Aseta oikeudet",
    'Valittu_paikka_ei_Katrina_tila': "Valittu paikka ei ole Katrinaan määritetty tila!",
    'Paikan_tiedot': "Paikan tiedot",
    'Ryhman_vaihtaminen': "Ryhmän vaihtaminen",
    'Valitse_jokin_tuote': "Valitse jokin tuote",
    'Aseta_tiedotteelle_ajastus': "Aseta tiedotteelle ajastus",
    'Tekstiviestien_lahetys': "Tekstiviestien lähetys",
    'Kerro_minulle_lisaa': "Kerro minulle lisää",
    'Nimi': "Nimi",
    'Sahkoposti': "Sähköposti",
    'Puhelin': "Puhelin",
    'Kysy_lisaa': "Kysy lisää",
    'Viestisi_on_lahetetty': "Viestisi on lähetetty",
    'Kiitos_kinnostuksesta_olemme_Sinuun_yhteydessa': "Kiitos kinnostuksesta, olemme Sinuun yhteydessä",
    'Virheita_lomakkeessa': "Virheitä lomakkeessa",
    'Kentan_arvo_lyhyt': "Kentän arvo on liian lyhyt",
    'Kentan_arvo_tyhja': "Kentän arvo ei saa olla tyhjä",
    'Kentan_arvo_ei_numero': "Kentän arvo pitää olla numero",
    'Virheellinen_paivamaara': "Päivämäärä on virheellinen (pitää olla muotoa pp.kk.vvvv)",
    'Vahvista_poisto': "Vahvista poisto?",
    'Pakollinen_tieto': "Pakollinen tieto",
    'Valinta_ei_saa_olla_tyhja': "Valinta ei saa olla tyhjä!",
    'Asetus_tallennettu': "Asetus tallennettu!",
    'Julkaistaan': "Julkaistaan",
    'Ei_julkaista': "Ei julkaista",
    'Varaustyyppia_ei_maaritetty': "Varaustyyppiä ei määritetty",
    'Kustannuspaikkaa_ei_ole_maaritetty': "Kustannuspaikkaa ei ole määritetty",
    'Lisaa_asiakas': "Lisää asiakas",
    'Tiedot_paivitetty_seuraaviin_kenttiin': "Tiedot päivitetty seuraaviin kenttiin",
    'Virheellinen_kellonaika': "Virheellinen kellonaika",
    'Loppuklo_ei_saa_olla_alkamisklo_aikaisempi': "Loppumisaika ei voi olla aikaisempi kuin alkamisaika",
    'Loppupvm_ei_saa_olla_alkamispvm_aikaisempi': "Loppumispäivämäärä ei voi olla aikaisempi kuin alkamispäivämäärä",
    'Tiedot_tallennettu': "Tiedot tallennettu!",
    'Kopioi': "Kopioi",
    'Mobiilikirjaukset': "Mobiilikirjaukset",
    'Vahvistus_esityksen_poisto': "Oletko varma että haluat poistaa tämän esityksen?",
    'Vahvistus_sivun_poisto': "Oletko varma että haluat poistaa tämän sivun?",
    'Henkilo_vuorossa': "Henkilö vuorossa",
    'Resursseja_ei_valittu': "Resursseja ei ole valittu",
    'Resurssien_valinta': "Resurssien valinta",
    'Valittu': "Valittu",
    'Kaste': "Kaste",
    'Vihkiminen': "Vihkiminen",
    'Siunaus': "Siunaus",
    'Virhe': "Virhe",
    'Sahkopostiosoitteet_asiakasrekisterista': "Sähköpostiosoitteet asiakasrekisteristä",
    'klo': "klo",
    'Tulosta': "Tulosta",
    'Muutoshistoria': "Muutoshistoria",
    'Toimituslomakkeen_kentta_tyhja': "Toimituslomakkeen yksi tai useampi pakollinen kenttä on tyhjä/virheellinen!",
    'Tarjoiluvaraus_tilaisuuteen': "Haluatko tehdä tarjoiluvarauksen tilaisuuteen?",
    'Tiedote_tilaisuudesta': "Haluatko tehdä tiedotteen tilaisuudesta?",
    'Info': "Info",
    'Muuta_nimea': "Muuta nimeä",
    'Paivamaara_puuttuu': "Päivämäärä puuttuu",
    'Tuntisuunnitelman_julkaisu_paalla': "Tuntisuunnitelman julkaisu on päällä, suunnitellut työajat on julkaistava Tuntisuunnittelun puolella.",
    'Varaukseen_valitut_paivat': "Varaukseen valitut päivät",
    'Leirikeskusvaraus': "Leirikeskusvaraus",
    'Ingressi_tyhja': "Ingressi ei saa olla tyhjä",
    'Sisaltoteksti_tyhja': "Sisältöteksti ei saa olla tyhjä",
    'Lukkarin_tiedot': "Lukkarin tiedot",
    'Sisalto': "Sisältö",
    'Kaytossa': "Käytössä",
    'Minuuttia': "Minuuttia",
    'Tallenna_tilastomerkintoja': "Tallenna tilastomerkintöjä",
    'Seuraavat_tiedot_puutteellisesti_taytetty': "Seuraavat tiedot puutteellisesti täytetty",
    'Kohtaamisen_paikka_pitaa_olla_valittuna': "Kohtaamisen paikka pitää olla valittuna",
    'Kohtaamisen_syy_pitaa_olla_valittuna': "Kohtaamisen syy pitää olla valittuna",
    'Perherakenne_pitaa_olla_valittuna': "Perherakenne pitää olla valittuna",
    'Ikaryhma_pitaa_olla_valittuna': "Ikäryhmä pitää olla valittuna",
    'Toimeentulo_pitaa_olla_valittuna': "Toimeentulo pitää olla valittuna",
    'Toteuttaja_pitaa_olla_valittuna': "Toteuttaja pitää olla valittuna",
    'Perherakenne_virheellinen': "Perherakenne virheellinen",
    'Kohtaamisen_syy_virheellinen': "Kohtaamisen syy virheellinen",
    'Kohtaamisen_syyt_yhteensa_eri_kun_perherakenteet_yhteensa': "Kohtaamisen syyt yhteensä eri kun perherakenteet yhteensä",
    'Ikaryhma_virheellinen': "Ikäryhmä virheellinen",
    'Ikaryhmat_yhteensa_eri_kun_perherakenteet_yhteensa': "Ikäryhmät yhteensä eri kun perherakenteet yhteensä",
    'Yhteistyon_nimi_puuttuu': "Yhteistyön nimi puuttuu",
    'Paattymisvuotta_ei_ole_merkitty': "Päättymisvuotta ei ole merkitty",
    'Paattymisvuosi_on_virheellinen': "Päättymisvuosi on virheellinen",
    'Lahetysjarjestojen_kanssa_solmittujen_sopimusten_maara_puuttuu': "Lähetysjärjestöjen kanssa solmittujen sopimusten määrä puuttuu",
    'Sopimusten_euromaara_puuttuu': "Sopimusten euromäärä puuttuu",
    'Vapaaehtoisten_maara_puuttuu': "Vapaaehtoisten määrä puuttuu",
    'Jumalanpalveluspaikkojen_maara_puuttuu': "Jumalanpalveluspaikkojen määrä puuttuu",
    'Lisatiedot_tilastointiin_tarkastamatta': "Lisätiedot tilastointiin tarkastamatta",
    'Tilastointitiedot_taydennetty': "Tilastointitiedot täydennetty",
    'Tyontekijoita_vahemman_kun_toteuttajat': "Työntekijöitä vähemmän kuin toteuttajia",
    'Kokoontumiskerrat_virheellinen': "Kokoontumiskertojen määrä virheellinen",
    'Ryhman_paasisalto_ei_ole_valittu': "Ryhmän pääsisältö ei ole valittu",
    'Paaasiallista_kohderyhmaa_ei_valittu': "Pääasiallista kohderyhmää ei ole valittu",
    'Taydentavaa_tietoa_kohderyhmasta_ei_valittu': "Täydentävää tietoa kohderyhmästä ei ole valittu",
    'Ruokakassien_lukumaara_virheellinen': "Ruokakassien lukumäärä virheellinen",
    'Retken_leirin_kesto_virheellinen': "Retken / Leirin kesto virheellinen",
    'Toteuttajaa_toteuttajia_ei_valittu': "Toteuttajaa / Toteuttajia ei ole valittu",
    'Seurakuntalaisten_maara_ei_saa_olla_0': "Seurakuntalaisten määrä ei saa olla 0, kun toteuttajaksi on valittu Seurakuntalainen",
    'Toimeentulo_virheellinen': "Toimeentulo virheellinen",
    'Toimeentulot_yhteensa_eri_kun_perherakenteet_yhteensa': "Toimeentulot yhteensä eri kun perherakenteet yhteensä",
    'Seurakuntalaisia_mutta_ei_toteuttajia': "Toteuttajien lukumäärään on lisätty seurakuntalaisia, mutta toteuttajaksi ei ole valittu seurakuntalaisia.",
    'Kohtien_lukumaarien_tulee_olla_yhta_suuret': "Perherakenne ja Ikäryhmä kohdan lukujen tulee olla yhtäsuuret",
    'Kohtaamisen_syy_liian_pieni': "Kohtaamisen syitä tulee olla vähintään yhtä monta kuin Perherakenne ja Ikäryhmä kohdan lukumäärät ovat",
    'Jasenten_lukumaara_virheellinen': "Jäsenten lukumäärä (keskimääräinen / kerta) virheellinen",
    'Lisatiedot_tilastointiin': "Lisätiedot tilastointiin",
    'Laheta_tilastotiedot_tiedote': "Olet lähettämässä lomaketta kirkkohallituksen tilastojärjestelmään. Jos lomaketta muokataan lähettämisen jälkeen, tulee se lähettää uudestaan.",
    'Laheta_tilastotiedot': "Lähetä tilastotiedot",
    'Jatka': "Jatka",
    'Tilastoinnin_tietojen_poiston_vahvistus': "Ohjelma tyhjentää aiemmin tallennetut tilastoinnin lisätiedot. Haluatko jatkaa?",
    'Kohtaamisten_lkm_virheellinen': "Kohtaamisten lukumäärä virheellinen",
    'Viimeisen_kohtaamisen_pvm_virheellinen': "Viimeisen kohtaamisen päivämäärä virheellinen",
    'Ei_tilastoida': "Ei tilastoida",
    'Tyosopimuksien_jaksoasetukset': "Työsopimuksien jaksoasetukset",
    'varaamisen_tiedot': "Varaamisen tiedot",
    'Vain_yksi_luokitus': "Tiedotteeseen valittu useampi kuin yksi luokitus!",
    'Lisaa_avainsanoja': "Lisää avainsanoja",
    'Liian_monta_avainsanaa': "Liian monta avainsanaa valittuna (maks. 10)!",
    'Tiedot_kohtaamisesta': "Tiedot kohtaamisesta",
    'tiedostoa_lahetetaan': "Tiedostoa lähetetään, odota hetki...",
    'virheellinen_tiedostopaate': "Virheellinen tiedostopääte",
    'tiedosto_lisatty_onnistuneesti': "Tiedosto lisätty onnistuneesti",
    'poista_tiedosto': "Poista tiedosto",
    'Kuvan_esikatselu': "Kuvan esikatselu",
    'sahkoposti_loki': "Sähköpostin lähetyshistoria",
    'Lisaa_yhteyshenkiloita': "Lisää yhteyshenkilöitä",
    'Liian_monta_yhteyshenkiloa': "Liian monta yhteyshenkilöä valittuna (maks. 10)!",
    'Kohderyhmaa_ei_valittu': "Kohderyhmää ei valittu!",
    'Tapahtumamuoto_ei_valittu': "Tapahtumamuoto ei valittu!",
    'Tilaisuuden_pvm_virheellinen': "Tilaisuuden päivämäärä virheellinen",
    'Osallistujamaara_virheellinen': "Osallistujamäärä virheellinen",
    'Toteuttajana_ollutta_erityistyomuotoa_ei_valittu': "Toteuttajana ollutta erityistyömuotoa ei valittu",
    'Kohdatut_lkm_virheellinen': "Kohdattujen henkilöiden lukumäärä virheellinen",
    'Vahtimestari_valinta_pakollinen': "Vahtimestari/Suntio -valinta pakollinen valitulle varaustyypille!",
    'Henkilo_pakollinen_vahtimestarille': "Valitsemallesi varautyypille Suntio/Vahtimestari valinta on määritelty pakolliseksi, valitse henkilöistä varaukseen varattava Suntio/Vahtimestari.",
    'a5_osallistujamaara_info': "Varauskejtun kävijämäärän tilastointitavaksi Kirkkohallituksen tilastointilomakkeelle on valittu keskimääräinen osallistujamäärä",
    'syotetty_arvo': "syötetty arvo",
    'add_client': "Lisää asiakas",
    'ekirjetta_lahettavaa_sivua_ei_maaritetty': "eKirjeen lähettävää sivua ei määritetty!",
    'yhtaan_vastaanottajaa_ei_valittu': "Yhtään vastaanottajaa ei valittu!",
    'kustannuspaikkaa_tyhja': "Kustannuspaikka ei saa olla tyhjä!",
    'kentan_arvo_tyhja': "Kentän arvo ei saa olla tyhjä!",
    'no_clients_or_groups_selected': "Yhtään henkilöä tai ryhmää ei valittu!",
    'send_sms': "Tekstiviestin lähetys",
    'date_invalid': "Päivämäärä on virheellinen!",
    'time_invalid': "Kellonaika on virheellinen!",
    'no_persons_selected': "Yhtään henkilöä ei ole valittu",
    'no_message': "Viesti ei saa olla tyhjä.",
    'message_is_too_long': "Liian pitkä viesti",
    'chars_max': "merkkiä, max",
    'send_ipost': "eKirjeen lähetys",
    'send_email': "Sähköpostiviestin lähetys",
    'no_title': "Otsikko ei saa olla tyhjä.",
    'no_role': "Roolia ei valittu!",
    'invalid_email': "Virheellinen sähköpostiosoite!",
    'invalid_phone': "Virheellinen puhelinnumero!",
    'invalid_ssn': "Virheellinen henkilötunnus!",
    'date_of_death_before_birth': "Kuolinpäivä ennen syntymäaika!",
    'birthdate_check': "Syntymäaika mahdollisesti virheellinen. Haluatko jatkaa?",
    'add_new_client': "Lisää uusi henkilö",
    'edit_client': "Muokkaa henkilön tietoja",
    'delete_client_removal': "Asiakkaan poiston varmistus",
    'client_deleted': "Asiakas poistettu!",
    'remove_client_from_company_confirm': "Haluatko varmasti poistaa yhteyshenkilön asiakaslistalta?",
    'client_name_empty': "Kutsumanimi ja sukunimi eivät saa olla tyhjät!",
    'minor_client_info': "Tallennettu alle 16 vuotiaan tiedot, pyydä huoltajan suostumus.",
    'grownup_client_info': "Muista suostumus ja tiedota asiakasta tietojen käytöstä.",
    'ssn_check': "Henkilötunnus mahdollisesti virheellinen. Haluatko jatkaa?",
    'clients_added_to_groups': "Asiakkaat lisätty valittuihin ryhmiin!",
    'delete_file_confirmal': "Haluatko varmasti poistaa valitun tiedoston?",
    'tietosuoja_ja_rekisteriselosteet': "Tietosuoja- ja rekisteriselosteet",
    'suntio': "suntio",
    'Henkilo_asiakasrekisterissa': "Asiakasrekisteristä löytyy jo samanniminen asiakas",
    'kavijamaara_kentat': "Kaikki/Ehtoolliselle osallistuneet",
    'Ryhmamuoto_muuttuu_info': "Jos muutat ryhmämuodon, tilastointia ei voi tehdä. Haluatko varmasti jatkaa?",
    'Valitse_asiakkaasta_naytettavat_kentat': "Valitse asiakkaasta näytettävät kentät",
    'Tyotehtavan_prioriteettia_ei_maaritetty': "Työtehtävän prioriteettiä ei määritetty!",
    'Paallekkaisia_varauksia_tarkea_prioriteetti': "Päällekkäisiä varauksia joissa tärkeä prioriteetti, varausta ei voida tallentaa!",
    'Paaryhmaa_ei_valittu': "Pääryhmää ei ole valittu",
    'passwords_dont_match': "Salasanat eivät täsmää!",
    'Toimituslomakkeen_tiedot': "Toimituslomakkeen tiedot",
    'Tayta_selitekentta': "Täytä selitekenttä!",
    'invalid_birthdate': "Virheellinen syntymäaika!",
    'invalid_date_of_death': "Virheellinen kuolinpäivä!",
    'Tallennettava_hautaus_pakollinen': "Tallennettava hautaus pakollinen valitulle varaustyypille!",
    'haluatko_varmasti_poistaa_asiakkaan': "Haluatko varmasti poistaa asiakkaan?",
    'asiakastietojen_tallennus_kysymys': "Varaustyyppi on muuttumassa.<br /><br />Haluatko voida palauttaa toimituslomakkeelle tallentamasi asiakastiedot,<br>jos vaihdat varaustyypin takaisin alkuperäiseksi?",
    'Aseta_prioriteetti': "Aseta prioriteetti",
    'Lataa_sivu': "Lataa sivu uudelleen.",
    'dummy': "dummy"
};
